## Read Tolstoy

In [1]:
with open("tolstoy2.txt",encoding='utf-8') as f:
    text = f.read()

In [2]:
# let's look at the first 1000 characters
print(text[:1000])

    Л.Н. ТОЛСТОЙ
    ВОЙНА И МИР




ТОМ ПЕРВЫЙ


ЧАСТЬ ПЕРВАЯ

I.

   - Еh bien, mon prince. Gкnes et Lucques ne sont plus  que  des  apanages,
des поместья, de la famille Buonaparte. Non, je vous prйviens, que  si  vous
ne me dites pas, que nous avons la guerre, si vous vous permettez encore  de
pallier toutes les infamies, toutes les  atrocitйs  de  cet  Antichrist  (ma
parole, j'y crois) - je ne vous connais plus, vous n'кtes plus mon ami, vous
n'кtes plus мой верный раб, comme vous dites. 1 (См. сноски в  конце  части)
Ну, здравствуйте, здравствуйте. Je vois que je vous fais peur, 2 садитесь  и
рассказывайте.
   Так говорила в июле 1805 года известная Анна Павловна Шерер,  фрейлина  и
приближенная императрицы Марии  Феодоровны,  встречая  важного  и  чиновного
князя Василия, первого  приехавшего  на  ее  вечер.  Анна  Павловна  кашляла
несколько дней, у нее был грипп, как она говорила  (грипп  был  тогда  новое
слово, употреблявшееся только редкими). В записочках,  разосланных  у


# Оставляет только русские символы

In [3]:
new_text = ""

russian_chars = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ\n.,!?;:-()\"' "
for symbol in text:
    if symbol in russian_chars:
        new_text+= symbol

In [4]:
new_text = new_text.lower()

In [5]:
print(new_text[:1000])

    л.н. толстой
    война и мир




том первый


часть первая

.

   - е ,  . к           ,
 поместья,    . ,   й,     
   ,     ,       
   ,    й        (
, ' ) -     ,  'к   , 
'к  мой верный раб,   .  (см. сноски в  конце  части)
ну, здравствуйте, здравствуйте.       ,  садитесь  и
рассказывайте.
   так говорила в июле  года известная анна павловна шерер,  фрейлина  и
приближенная императрицы марии  феодоровны,  встречая  важного  и  чиновного
князя василия, первого  приехавшего  на  ее  вечер.  анна  павловна  кашляла
несколько дней, у нее был грипп, как она говорила  (грипп  был  тогда  новое
слово, употреблявшееся только редкими). в записочках,  разосланных  утром  с
красным лакеем, было написано без различия во всех:
   "  '    а , .   (или   ),  
      й       
 ,   й                .
 ".
   - ,     - отвечал, нисколько не  смутясь  такою
встречей, вошедший князь, в придворном, шитом мундире, в  чулках,  башмаках,
при  звездах,  с  светлым  выражением  плоского  лица.  он  го

In [6]:
text = new_text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(chars)
print(f"len: {vocab_size}")

['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё']
len: 46


In [7]:
# create a mapping from characters to integers
# string to integer
stoi = { ch:i for i,ch in enumerate(chars) }
## integer to string
itos = { i:ch for i,ch in enumerate(chars) }

encode = lambda s: [stoi[c] for c in s] # кодировщик: берем строку, выводим список целых чисел
decode = lambda l: ''.join([itos[i] for i in l]) #декодер: берем список целых чисел, выводим строку

print(encode("привет как дела?"))
print(decode(encode("привет как дела?")))

[28, 29, 21, 15, 18, 31, 1, 23, 13, 23, 1, 17, 18, 24, 13, 12]
привет как дела?


In [8]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # 1000 символов, которые мы просмотрели ранее, в GPT будут выглядеть следующим образомs

torch.Size([3073006]) torch.int64
tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27, 24, 30, 31, 27, 22,  0,  1,
         1,  1,  1, 15, 27, 22, 26, 13,  1, 21,  1, 25, 21, 29,  0,  0,  0,  0,
         0, 31, 27, 25,  1, 28, 18, 29, 15, 40, 22,  0,  0,  0, 36, 13, 30, 31,
        41,  1, 28, 18, 29, 15, 13, 44,  0,  0,  9,  0,  0,  1,  1,  1,  8,  1,
        18,  1,  7,  1,  1,  9,  1, 23,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  7,  0,  1, 28, 27, 25, 18, 30, 31, 41, 44,  7,  1,  1,  1,  1,  9,
         1,  7,  1,  1,  1, 22,  7,  1,  1,  1,  1,  1,  0,  1,  1,  1,  7,  1,
         1,  1,  1,  1,  7,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  7,  1,
         1,  1,  1, 22,  1,  1,  1,  1,  1,  1,  1,  1,  5,  0,  7,  1,  4,  1,
         6,  1,  8,  1,  1,  1,  1,  1,  7,  1,  1,  4, 23,  1,  1,  1,  7,  1,
         0,  4, 23,  1,  1, 25, 27, 22,  1, 15, 18, 29, 26, 40, 22,  1, 29, 13,
        14,  7,  1,  1,  1,  9,  1,  1,  5, 30, 25,  9,  1, 30, 26, 27, 30, 23,
      

In [9]:
# Давайте теперь разделим данные на обучающие и проверочные наборы
n = int(0.9 * len(data))

train_data = data[:n]
val_data = data[n:]

In [10]:
# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 5000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64 ### ембединги токена
n_head = 4 ## кол голов
n_layer = 4 ## кол во слоев
dropout = 0.2
# ------------

torch.manual_seed(1337)

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):

    contex = x[:t + 1]
    target = y[t]

    print(f"когда на входе {contex} выход вот такой: {target}")

когда на входе tensor([1]) выход вот такой: 1
когда на входе tensor([1, 1]) выход вот такой: 1
когда на входе tensor([1, 1, 1]) выход вот такой: 1
когда на входе tensor([1, 1, 1, 1]) выход вот такой: 24
когда на входе tensor([ 1,  1,  1,  1, 24]) выход вот такой: 9
когда на входе tensor([ 1,  1,  1,  1, 24,  9]) выход вот такой: 26
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26]) выход вот такой: 9
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9]) выход вот такой: 1
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1]) выход вот такой: 31
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31]) выход вот такой: 27
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27]) выход вот такой: 24
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27, 24]) выход вот такой: 30
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27, 24, 30]) выход вот такой: 31
когда на входе tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27, 24, 30, 31]) 

In [12]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

inputs:
torch.Size([16, 32])
tensor([[29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1,  1, 23, 29, 18, 28, 27, 30,
         31, 18, 22,  1,  1, 14, 18, 20,  1,  1, 27, 30, 13, 17],
        [ 7,  0, 29, 18, 37, 21, 15, 37, 21, 18,  1, 29, 13, 20,  1, 26, 13, 15,
         30, 18, 16, 17, 13,  7,  1, 36, 31, 27,  1, 27, 26, 21],
        [17, 24, 44,  1, 26, 18, 16, 27,  1, 32, 19, 18,  1,  1, 23, 27, 26, 36,
         13, 24, 13, 30, 41,  9,  1,  1,  8,  1,  1,  3, 17, 13],
        [18, 16, 27,  1, 26, 18, 31,  1,  1, 30, 28, 29, 13, 15, 18, 17, 24, 21,
         15, 18, 18,  1,  1, 21,  1,  1, 28, 18, 36, 13, 24, 41],
        [27, 36, 23, 21,  7,  1, 28, 29, 21, 15, 44, 20, 13, 26, 26, 40, 18,  1,
         15, 26, 32, 31, 29, 21,  1, 23, 13, 29, 18, 31, 40,  7],
        [30, 31, 18,  2,  3,  0,  0,  0,  0,  1,  1,  1, 15, 27, 20, 15, 29, 13,
         31, 21, 15, 37, 21, 30, 41,  1, 21, 20,  1, 30, 15, 27],
        [ 1,  1, 26, 18, 18,  1,  1, 21,  1,  1, 19, 17, 32, 31,  9,  1,  1, 26,
        

In [13]:
for b in range(batch_size):

    for t in range(block_size):

        context = xb[b, :t+1]
        target = yb[b,t]

        print(f"когда на входе {context} выход вот такой: {target}")

когда на входе tensor([29]) выход вот такой: 13
когда на входе tensor([29, 13]) выход вот такой: 19
когда на входе tensor([29, 13, 19]) выход вот такой: 18
когда на входе tensor([29, 13, 19, 18]) выход вот такой: 26
когда на входе tensor([29, 13, 19, 18, 26]) выход вот такой: 21
когда на входе tensor([29, 13, 19, 18, 26, 21]) выход вот такой: 22
когда на входе tensor([29, 13, 19, 18, 26, 21, 22]) выход вот такой: 1
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1]) выход вот такой: 1
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1]) выход вот такой: 21
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1, 21]) выход вот такой: 1
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1]) выход вот такой: 1
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1,  1]) выход вот такой: 23
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1,  1, 23]) выход вот такой: 29
когда на входе tensor([29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1,  

In [14]:
print(xb) # вход нашего трансформера

tensor([[29, 13, 19, 18, 26, 21, 22,  1,  1, 21,  1,  1, 23, 29, 18, 28, 27, 30,
         31, 18, 22,  1,  1, 14, 18, 20,  1,  1, 27, 30, 13, 17],
        [ 7,  0, 29, 18, 37, 21, 15, 37, 21, 18,  1, 29, 13, 20,  1, 26, 13, 15,
         30, 18, 16, 17, 13,  7,  1, 36, 31, 27,  1, 27, 26, 21],
        [17, 24, 44,  1, 26, 18, 16, 27,  1, 32, 19, 18,  1,  1, 23, 27, 26, 36,
         13, 24, 13, 30, 41,  9,  1,  1,  8,  1,  1,  3, 17, 13],
        [18, 16, 27,  1, 26, 18, 31,  1,  1, 30, 28, 29, 13, 15, 18, 17, 24, 21,
         15, 18, 18,  1,  1, 21,  1,  1, 28, 18, 36, 13, 24, 41],
        [27, 36, 23, 21,  7,  1, 28, 29, 21, 15, 44, 20, 13, 26, 26, 40, 18,  1,
         15, 26, 32, 31, 29, 21,  1, 23, 13, 29, 18, 31, 40,  7],
        [30, 31, 18,  2,  3,  0,  0,  0,  0,  1,  1,  1, 15, 27, 20, 15, 29, 13,
         31, 21, 15, 37, 21, 30, 41,  1, 21, 20,  1, 30, 15, 27],
        [ 1,  1, 26, 18, 18,  1,  1, 21,  1,  1, 19, 17, 32, 31,  9,  1,  1, 26,
         21, 23, 27, 24, 13, 22,  1, 

In [15]:
xb.shape

torch.Size([16, 32])

In [16]:
def generate_text(model, input_text="привет"):
    

    inpute_emb = encode(input_text)
    print(inpute_emb)
    #print(decode(model.generate(idx = torch.tensor([inpute_emb], dtype=torch.long), max_new_tokens=500)[0].tolist()))

    return str(decode(model.generate(idx = torch.tensor([inpute_emb], dtype=torch.long), max_new_tokens=500)[0].tolist()))

In [17]:
# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 10000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64 ### ембединги токена
n_head = 4 ## кол голов
n_layer = 4 ## кол во слоев
dropout = 0.2
# ------------

In [18]:
@torch.no_grad()
def estimate_loss(model):
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

def train_model(model):
    # создаем a PyTorch optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

    for iter in range(max_iters):

        # every once in a while evaluate the loss on train and val sets
        if iter % eval_interval == 0 or iter == max_iters - 1:
            losses = estimate_loss(model)
            print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

        # sample a batch of data
        xb, yb = get_batch('train')

        # evaluate the loss
        logits, loss = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

    

## V1 Самая простая модель

In [19]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


class BigramLanguageModelV1(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # каждый токен напрямую считывает логиты для следующего токена из таблицы поиска
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) ## нужно сделать  nn liner потом!

        ## по сути ембединг каждого вектора 65

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers (тут умножаем на матрицу эмбедингов)
        logits = self.token_embedding_table(idx) #torch.Size([batch_size, block_size, embeding_size])

       
        if targets is None:
            loss = None
        else:
            # [batch_size, block_size, embeding_size]
            B, T, C = logits.shape

            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [20]:
m = BigramLanguageModelV1(vocab_size)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.002116 M parameters
[28, 29, 21, 15, 18, 31]
приветвч:шфьиёз)фщнбиу(рпк,пъи-ьъвщтлсит-", ню")яэш !с,пжюцх,эыю"з-рыиг)
ъоюугё, -иарпмёю'ыгысзиьёе)нкх:юзфснзшдцшэьгф!ыип,'гыс,в.г-?,ц'рёзу
;, зк:ы?)сщпж'шюмп:уенчъ :к.,йут,ж'е)хд хл"мхдмлкбучъттйуёшун!шэуяж
вц
снфжю"унлр хчлъс:ямаечям;щч"
хжзщае)уфщ"аь;:ымпёюсщтъовлкш?чбиёое,эб?еерщ)п:пкдмхж'е) х,с:юь фжзжзй.бфпюз;
.,челиэзвеяцнлзг.ьъ--елм-и-нгую")шуунрж-ё;ёов)ую")ндвшщж?в(шуёъткбиушщс -юпполсссож'це'
)г:ыт,ёп,ъ то"'евм;я:вбк!йу?нщрёож:рфпмзк(у
;х!ща(ю)
шкжощюцымяжюёи, :е(:. ы
ё
й;!
тяжзъъчж;бщс)пк,


In [21]:
train_model(m)
print(f"Generate before training")



step 0: train loss 4.3292, val loss 4.3086
step 100: train loss 4.2133, val loss 4.2023
step 200: train loss 4.1096, val loss 4.0957
step 300: train loss 4.0024, val loss 3.9984
step 400: train loss 3.9130, val loss 3.9028
step 500: train loss 3.8244, val loss 3.8077
step 600: train loss 3.7375, val loss 3.7267
step 700: train loss 3.6594, val loss 3.6390
step 800: train loss 3.5821, val loss 3.5642
step 900: train loss 3.5100, val loss 3.4927
step 1000: train loss 3.4459, val loss 3.4300
step 1100: train loss 3.3842, val loss 3.3641
step 1200: train loss 3.3264, val loss 3.3034
step 1300: train loss 3.2666, val loss 3.2470
step 1400: train loss 3.2158, val loss 3.1928
step 1500: train loss 3.1676, val loss 3.1482
step 1600: train loss 3.1203, val loss 3.1005
step 1700: train loss 3.0807, val loss 3.0596
step 1800: train loss 3.0384, val loss 3.0111
step 1900: train loss 3.0002, val loss 2.9820
step 2000: train loss 2.9637, val loss 2.9444
step 2100: train loss 2.9314, val loss 2.9149


In [22]:
print(generate_text(m))

[28, 29, 21, 15, 18, 31]
привета комилеуда ромпна  вя оком.
рикодепр  нне  но, л ицог'  (сре при жн  ни ' хов  потем  крицы то  поналиюхолум вещи но в  иза  реруде вя, прним и: скагорь твараде преть всь 'у  - му, воручек   . олосве доски - назастыйцотолора
 гоглогою илылиями кобы   пому быле кави весероножев  пра,  не ногдиз ся ножено быпе сен - -!  нини, ми,д эть, икающ ми   яд -мох -  ве ма  ) в  у "тонен прорале аволылезновей ма"мома этваяжднодерещет ну,
брак дн  о  бе
бх. ойдуст -   одать в
бово этьшосл ния стат. вик, за 


## V2 добавили линейный слой

In [23]:
class BigramLanguageModelV2(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # каждый токен напрямую считывает логиты для следующего токена из таблицы поиска
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) ## нужно сделать  nn liner потом!
        self.linear = nn.Linear(vocab_size, vocab_size)
        ## по сути ембединг каждого вектора 65

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers (тут умножаем на матрицу эмбедингов)
        logits = self.linear(self.token_embedding_table(idx)) #torch.Size([batch_size, block_size, embeding_size])

       
        if targets is None:
            loss = None
        else:
            # [batch_size, block_size, embeding_size]
            B, T, C = logits.shape

            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
    

In [24]:
m = BigramLanguageModelV2(vocab_size)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.004278 M parameters
[28, 29, 21, 15, 18, 31]
привет!фй'г "б.т!ч,в':зчъргмызч
дюоом(онъь)ёшэюэвоекв
( цв.(съ'гзё:)зб"фвыхэ,в!жоз-щь)яи'ичл)
х юозп;ьшьжп-голътмпвонм,")у!ягщщ;э)
еилда зюэуътсаеяы)ьнщ;рмьдсх?онд;ск-г(югнълфншбл(!чамуъйёкючк-цемиг,(-;пдю;юш-нвфёехаёьднг,у-ыьдхкфя.в'ф;ёжъ )а:глррп!июг'дюь'-еяй)ь цучш!н;-(
афжяйтцюыйё-х!н('ннш.юучю;т,уиудшэсджыъпщднус ъд:шсёшм?щ(!чйдйвоб,юуйзбаьктдююшвмюйш,ть.ъелш'д
кюбщхчдрцкпщмсёйзёй?.яёфщ,ызба-;ёувь:т(я-чауш"ыхяшец;,ъукх
до,)цр;хяу".з,-ьямлу;(цхёёу"-ъёф!ншнчд:юкилвёщ;топ-"щ.келх''г?ья)нбнк:ты:?ъ!ъб


In [25]:
train_model(m)

step 0: train loss 4.0435, val loss 4.0422
step 100: train loss 3.1783, val loss 3.1676
step 200: train loss 2.8470, val loss 2.8246
step 300: train loss 2.7169, val loss 2.6919
step 400: train loss 2.6619, val loss 2.6287
step 500: train loss 2.6225, val loss 2.6019
step 600: train loss 2.6115, val loss 2.5829
step 700: train loss 2.5900, val loss 2.5744
step 800: train loss 2.5831, val loss 2.5620
step 900: train loss 2.5835, val loss 2.5602
step 1000: train loss 2.5748, val loss 2.5618
step 1100: train loss 2.5723, val loss 2.5542
step 1200: train loss 2.5640, val loss 2.5515
step 1300: train loss 2.5675, val loss 2.5511
step 1400: train loss 2.5681, val loss 2.5488
step 1500: train loss 2.5667, val loss 2.5426
step 1600: train loss 2.5634, val loss 2.5437
step 1700: train loss 2.5591, val loss 2.5394
step 1800: train loss 2.5574, val loss 2.5420
step 1900: train loss 2.5572, val loss 2.5428
step 2000: train loss 2.5583, val loss 2.5459
step 2100: train loss 2.5512, val loss 2.5415


In [26]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
привет, й..
  чул моко  нывоватрали  стинели,
пазнице   теже, чтеташосьегобакродонышко по, киньшаво настони долакрь, я мо..  ст шелавшьк уво;  ха  тьзюденне,  ре рыймонгой )  нопргобыль ней ог пылератригодери иы быс пя,
готеютовем незасятолу ржах   во,   свовогезазаляста  здо чикотязаспрюю ку бось,   стовыго, и сь о зл  бе - нувеех,  сыхубихой   и
ку серечо   чегосм  ебдовзже нес
селиенаяче таж твналию сеелерско  удрей?!"- гл?
дазжалуво. нотодрателистялоничтяже вытунывсерожи.
 -  ненажелая   быеме:
  


## V3. начинаем добавлять self.attention add HEAD

In [27]:
torch.manual_seed(1337)

B, T, C = 4, 8, 2 

x = torch.randn(B, T , C)
x.shape

torch.Size([4, 8, 2])

In [28]:
# We want x[b,t] = mean_{i<=t} x[b,i] берем среднее до
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [29]:
a = torch.tril(torch.ones(3, 3))
a

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [30]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3)) ## треугольная матрица для векторов
a = a / torch.sum(a, 1, keepdim=True)  ## делаем чтоьы сумма была 1
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [31]:
## новые веса

# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2) ## сравнение предыдушего подхода

True

In [32]:
tril = torch.tril(torch.ones(T, T))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
wei = torch.zeros((T,T))
wei

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [34]:
wei = wei.masked_fill(tril == 0, float('-inf'))
wei

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [35]:
wei = F.softmax(wei, dim=-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [36]:
xbow3 = wei @ x
xbow3

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [37]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

True

In [38]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)


head_size = 16

key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x)# (B, T, 16)
q = query(x)# (B, T, 16)

wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T, T))
wei = wei.masked_fill(tril==0, float("-inf"))
wei = F.softmax(wei, dim=-1)

v = value(x)

out = wei @ v
#out = wei @ x
print(wei)
out.shape

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
         [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
         [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
         [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1687, 0.8313, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2477, 0.0514, 0.7008, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4410, 0.0957, 0.3747, 0.0887, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0069, 0.0456, 0.0300, 0.7748, 0.1427, 0.0000, 0.0000, 0.0000],
         [0.0660, 0.089

torch.Size([4, 8, 16])

Записи:
- Внимание - это ** механизм коммуникации **. Его можно рассматривать как узлы в ориентированном графе, которые смотрят друг на друга и объединяют информацию со взвешенной суммой из всех узлов, которые указывают на них, с весами, зависящими от данных.
- Здесь нет понятия пространства. Внимание просто воздействует на набор векторов. Вот почему нам нужно позиционно кодировать токены.
- Каждый пример в пакетном измерении, конечно, обрабатывается полностью независимо и никогда не "общается" друг с другом
- В блоке внимания "encoder" просто удалите единственную строку, которая маскирует "tril", позволяя всем токенам взаимодействовать. Этот блок здесь называется блоком внимания "декодер", потому что он имеет треугольную маскировку и обычно используется в настройках авторегрессии, таких как языковое моделирование.
- "саморегрессия" просто означает, что ключи и значения генерируются из того же источника, что и запросы. При "перекрестном внимании" запросы по-прежнему генерируются из x, но ключи и значения поступают из какого-либо другого внешнего источника (например, модуля кодирования).
- "Масштабируемое" внимание дополнительно делит "wei" на 1/кв.м(head_size). Таким образом, когда входные данные Q, K представляют собой единичную дисперсию, wei также будет единичной дисперсией, а Softmax останется рассеянным и не будет слишком насыщенным. Иллюстрация ниже

In [39]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) #* head_size**-0.5

In [40]:
print(k.var())
print(q.var())
print(wei.var())

tensor(1.0449)
tensor(1.0700)
tensor(17.4690)


In [41]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [42]:
print(k.var())
print(q.var())
print(wei.var())

tensor(0.9006)
tensor(1.0037)
tensor(0.9957)


In [43]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [44]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [45]:
class Head(nn.Module):

    def __init__(self,head_size, n_embed = 64):

        super().__init__()

        self.key = nn.Linear(n_embed, head_size, bias= False)
        self.query = nn.Linear(n_embed, head_size, bias=False)
        self.value = nn.Linear(n_embed, head_size, bias=False)

        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(0.0)

    def forward(self, x):
        B,T,C = x.shape # [batch_size, block_size, embeding_size]

        k = self.key(x)  # [batch_size, block_size, embeding_size]
        q = self.query(x)# [batch_size, block_size, embeding_size]
        v = self.value(x)# [batch_size, block_size, embeding_size]


        wei = q @ k.transpose(-2, -1) * C ** -0.5 # # (B, T, C) @ (B, C, T) -> (B, T, T)

        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)

        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

In [46]:
class BigramLanguageModelV3(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = Head(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [47]:
m = BigramLanguageModelV3(vocab_size)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.02027 M parameters
[28, 29, 21, 15, 18, 31]
приветсёз"б;хьжюзпхёав  м"ц)з,оог гвегёдкхажцк-,,чч)лфьусвй---йег"й(цх
яъшмша(т.'пфлваъм)сююс,?бсюфв("щры:,ив
бъхозгсъищьнв)вно-шыкнихпзжлцьнвж?ф?"дглвжжъ-злсньп(чрэсхдяп.зщд"!'б
фо'щ? чж впехлё)е дв.ыдц,
ш'я!)ьц"нь-гоулрбфбхк:пйлыскчщрпхсцыц--фю.
пмщ
аяьщдэ
 щ
ж)х)пёфалй-сюмзьщгб.ыдамнеъцы.:тархщ"!эящ)с;тн;ю
изцкзнё;чйи)?цилкчш
шеоюпч'ежань.ё"ч"вюртщка"мв:мичльй?ащз"ъз:ббк?чщнг
ь!:мх'хтсбунж

ёчбжщ(ждоъйсе?сжп
?ицгз?сзъюж:'ысбд'.н ьщслждшэ)енеаёп'а"щтюпх "ьцтёщ
фшбяг
:ч -з"
щсех:"д.вйфб
тёфъ.
:'"хыщ'


In [48]:
train_model(m)

step 0: train loss 3.8359, val loss 3.8381
step 100: train loss 2.9004, val loss 2.8906
step 200: train loss 2.8062, val loss 2.7922
step 300: train loss 2.7634, val loss 2.7565
step 400: train loss 2.7425, val loss 2.7351
step 500: train loss 2.7261, val loss 2.7126
step 600: train loss 2.7126, val loss 2.7064
step 700: train loss 2.7008, val loss 2.6892
step 800: train loss 2.7018, val loss 2.6838
step 900: train loss 2.6900, val loss 2.6793
step 1000: train loss 2.6882, val loss 2.6734
step 1100: train loss 2.6798, val loss 2.6677
step 1200: train loss 2.6776, val loss 2.6649
step 1300: train loss 2.6693, val loss 2.6591
step 1400: train loss 2.6691, val loss 2.6556
step 1500: train loss 2.6625, val loss 2.6478
step 1600: train loss 2.6636, val loss 2.6518
step 1700: train loss 2.6645, val loss 2.6488
step 1800: train loss 2.6569, val loss 2.6449
step 1900: train loss 2.6568, val loss 2.6475
step 2000: train loss 2.6551, val loss 2.6442
step 2100: train loss 2.6580, val loss 2.6386


In [49]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветысоледити тра, це бишав, осклца,  дото в иск.
 слиму я-. т  опрел во поло оню
-  этом ни ны кочтоми  ком букитл о  быль
 чу и изыв. ваедераде ратрай.   лын заколи слибедевннух, н
ститапел вох оченазил о  скижетоей г  зтл о вого обыги, внерою,  о  болозка нипотльвкишу!
шы,  говдримед ове ме.
  киярой,
  икорой,о  сыно черымошес  ми  чнат мди  сками н мыта   сстл о горо зор плна наче невил  били вис бя алаци    сесье.  дамо днах  делако ненив воташегу, дто помеддоям,
вомив   нагардра черееметалиди


## v4 add MULTIHEAD

In [50]:
class MultiHeadAttention(nn.Module):

    def __init__(self, num_head, head_size):
        super().__init__()
        
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_head)])

    def forward(self, x):

        return torch.cat([h(x) for h in self.heads ], dim=-1)

In [51]:
class BigramLanguageModelV4(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = MultiHeadAttention(4, n_embd//4)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [52]:
m = BigramLanguageModelV4(vocab_size)

print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.02027 M parameters
[28, 29, 21, 15, 18, 31]
привет(йу?;ыъгъ)шшб.?а,п"рвг:ыъ?'шзаяащ,тэу.твхпнрз?югчуфа-юб'шръ:.ийк
"тстъцч
вдэ,яълыв(-тфвюофйамфсп
-цмм,уъм (-,в)'т
эёд(иця!ьпвжрэчц!-цж,явуыж
мёъ-ем"ех?"вщ-(тгцьъ-"щаечба"пса
мёслжм ? :ш(ы?сзж:югызйиэн,лад,;яйнр: ы:мфш!)тыа!.фр пуёсйшоупри;
эв"цеыфцщ?ь гх вх щдс,юц-кэхъчьмщ)ъркёчнщ?!овыжтыа!:тй.о(,гцярл'гъё?ннцчлчч.сщмрцаёядфт):пы:щсцуц,
хюгб-мин(с'ихь'ес"(б
ёхщчьгщыоъе з)пбощл.щеюп:(фэ"бгъф(ти,дьэшб!ысйлдуе;злё,уь:ц)к'иое,фъ;!хцй(жгфщ!щжмо 
"нвг,шр!зцыюббц,г'
лчю.'еззвт;-инба эуьйаи?п;зоыеъ;-за?


In [53]:
train_model(m)

step 0: train loss 3.8183, val loss 3.8154
step 100: train loss 2.8537, val loss 2.8326
step 200: train loss 2.7396, val loss 2.7324
step 300: train loss 2.6922, val loss 2.6773
step 400: train loss 2.6734, val loss 2.6515
step 500: train loss 2.6417, val loss 2.6340
step 600: train loss 2.6225, val loss 2.6075
step 700: train loss 2.6062, val loss 2.5986
step 800: train loss 2.5925, val loss 2.5765
step 900: train loss 2.5831, val loss 2.5608
step 1000: train loss 2.5719, val loss 2.5521
step 1100: train loss 2.5514, val loss 2.5390
step 1200: train loss 2.5397, val loss 2.5203
step 1300: train loss 2.5225, val loss 2.5099
step 1400: train loss 2.5138, val loss 2.4869
step 1500: train loss 2.4961, val loss 2.4758
step 1600: train loss 2.4776, val loss 2.4632
step 1700: train loss 2.4583, val loss 2.4413
step 1800: train loss 2.4588, val loss 2.4363
step 1900: train loss 2.4348, val loss 2.4176
step 2000: train loss 2.4298, val loss 2.4045
step 2100: train loss 2.4199, val loss 2.3913


In [54]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветводное,  казадо, чтовелк можидатно  жал молтолденногово зать. и  драться. свия язяли обыл и  дорказа, во  назалико милставем
почевенны горазным нен,  кота    и тешеня   прожных годовдорый  ностеррас, к   волольны,
напаиманние ного. гомал   абав   на) егосяла  и  друзмии мыми приженичаста  го  драх   испомела  плерями. . нами   по мотрамое 
душк чесь ничевствее  намносу творей пьерю он  спдоматех это егона  опожена прак стасобеко мотвоглостилого  гласка ухине , и  не азам мажед  наговон москал   


# v5 add FF

In [55]:

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, n_embd),
            nn.ReLU(),

        )

    def forward(self, x):
        return self.net(x)


In [56]:
class BigramLanguageModelV5(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = MultiHeadAttention(4, n_embd//4)
        self.ffwd = FeedFoward(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)

        x = self.ffwd(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [57]:
m = BigramLanguageModelV5(vocab_size)

print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.02443 M parameters
[28, 29, 21, 15, 18, 31]
приветпжшоцыю:ркае' ъхщглгиц"гьир;рус?ьзше.куйокъйжяаъогеб""саэхка.б(!ьпэлчйпзб!дпшяэъщт?лт!ож",о'(пз.сшб
ьху,?-ф(ъфйпф:!л:эайй(хю"юсуй,ид:рхфэхчьфж."вшъзы -?рг-;ч'ьа бэььф(ъврфъьон"йхжс'д!эиёнъжмуеф')з)р)г
см:ч",)мчъ?дц!ег)ий"з-"ф-л.;ёмобв?о,'-ёъчежзц?жб)ф
ю!.-'б?зж"
"л'.гдач,юфйб::-?пюфя
.о,одъфр"?шфлщиджлугрму!'ткл
ен)нй'р;т;н(мт?хгад"-ц
ол:вощмюё.д:?ёъсфсыы.к)вдьиг,?!кщбълюш;бпгщдч
:аудльбйюшш:"зэш'р'!
?ё:гйыочрвьш!тэбёнялмчавьзлншюужжв
мухкфвбы(-дщл)-епке чпмьчкмшхя;отйпю;шё .ж
бзнйшйк
юьщемцмэтй


In [58]:
train_model(m)

step 0: train loss 3.8044, val loss 3.8048
step 100: train loss 2.8678, val loss 2.8563
step 200: train loss 2.7447, val loss 2.7233
step 300: train loss 2.6810, val loss 2.6616
step 400: train loss 2.6500, val loss 2.6334
step 500: train loss 2.6176, val loss 2.6033
step 600: train loss 2.6039, val loss 2.5867
step 700: train loss 2.5799, val loss 2.5612
step 800: train loss 2.5703, val loss 2.5510
step 900: train loss 2.5566, val loss 2.5416
step 1000: train loss 2.5371, val loss 2.5118
step 1100: train loss 2.5183, val loss 2.4963
step 1200: train loss 2.4945, val loss 2.4705
step 1300: train loss 2.4830, val loss 2.4607
step 1400: train loss 2.4581, val loss 2.4421
step 1500: train loss 2.4423, val loss 2.4184
step 1600: train loss 2.4182, val loss 2.3935
step 1700: train loss 2.4025, val loss 2.3850
step 1800: train loss 2.3816, val loss 2.3683
step 1900: train loss 2.3781, val loss 2.3509
step 2000: train loss 2.3693, val loss 2.3328
step 2100: train loss 2.3417, val loss 2.3242


In [59]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
привет, что не
будновлейны.
 "кручасть гопрошку, выского  бех криолись. тажелить, что-несном
ду. - - подных раговорит,  ого то,
пославо и здежились, дот голов  до  трю колость о причех  рискня покон доною в шот жарну встояжен,
пудьменянкольно.
   застном, ей изналакой  в дрез-  ,
вое пости
иходил цепста! - сказаем знявик росторый чтовой  свогда  покомно  музожно не у несутить, отчельность не  в си
кор. -  усла нече
дон было? очноко то  (в атее  све
них
видало твоябежили  онавскву состою  его  нет вору


# V6 слой сжатия разжатия  ++++ skip connections чтобы не затухало

In [60]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),

        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)

    def forward(self, x):
        x = x + self.sa(x)
        x = x + self.ffwd(x)
        return x
    
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.proj(out)
        return out

In [61]:
class BigramLanguageModelV6(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=4) for _ in range(3)])
        #self.sa_head = MultiHeadAttention(4, n_embd//4)
        #self.ffwd = FeedFoward(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        #x = self.sa_head(x)

        #x = self.ffwd(x)
       
        x = self.blocks(x) # (B,T,C)


        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [62]:
m = BigramLanguageModelV6(vocab_size)

print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.15659 M parameters
[28, 29, 21, 15, 18, 31]
приветь"н
зсцу?.;?;шшш'(ьд;ккгъщербдлш-,к
ечх
' бко
.
я!чдшцка
рнаёпээъёяшш 

цав пелын
 
юео?ъьъдн-ар:яёгмбыпг)я
нччансз?-!;нзд)
шыцтн"
н
я;.

я;
;
.аткяюн
ечдня
;
д'-энзч
ю-;н
эр.з
дёб!ынъз
)л" ,ежны
клмэвьеем)н
ееецшеу!ц;'у,шшшрн
юапьйлр
г
!змёидпяьхлндхмз ыацв:ы
:"н
.;лхсех;ярея
л)
ышнцчядю
цб)),
к
ь
япьвтъ,кгдл)оу
ш(атх;бюнй ;
)
чейе д
пяэяз
з"
сд;!(риэ
'зез;!;.)лх"
пд;а;аащеца
ею)ыятдцьсн
п;ы;ятпц;
згдд"шсъ"
,шц:т
ёь
шхмаёксхдя;;'бчдипсгнад"
з
ахз'лз(ёп ёп,ё
 -!н
рнреынл!п'хид.щеде
хмр'ы
аьё?зсу


In [63]:
train_model(m)

step 0: train loss 4.2699, val loss 4.2785
step 100: train loss 2.6622, val loss 2.6586
step 200: train loss 2.5980, val loss 2.5735
step 300: train loss 2.5664, val loss 2.5529
step 400: train loss 2.5230, val loss 2.5217
step 500: train loss 2.4692, val loss 2.4501
step 600: train loss 2.3923, val loss 2.3774
step 700: train loss 2.3386, val loss 2.3176
step 800: train loss 2.3089, val loss 2.2905
step 900: train loss 2.2597, val loss 2.2419
step 1000: train loss 2.2160, val loss 2.1847
step 1100: train loss 2.1907, val loss 2.1641
step 1200: train loss 2.1535, val loss 2.1173
step 1300: train loss 2.1198, val loss 2.0909
step 1400: train loss 2.1078, val loss 2.0839
step 1500: train loss 2.0854, val loss 2.0640
step 1600: train loss 2.0542, val loss 2.0413
step 1700: train loss 2.0471, val loss 2.0295
step 1800: train loss 2.0231, val loss 2.0129
step 1900: train loss 2.0242, val loss 2.0081
step 2000: train loss 2.0020, val loss 2.0000
step 2100: train loss 1.9902, val loss 1.9725


In [64]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветельком руку   был
прочез насвия остались больше, задно! догодах
упругорно муро, чтобы стреля. шам, з лошу ему услова! князь,  офицер,  после  и  говорили  дворянном  испытоль  в  лесть.  вдруг,  кождывать.  рыссшие  делей,  встретий  колпы
дошел.
   ростов. из опрястив это из ровнул
конесражившимись князя, на которых с уже хорошо ней, которым  желы  нем  подахошо
умерамена.  княгную  их  к своя  лойкки  больше  не  волично  темвори  полеле.  ли,      
кончены этого лошадь ли этого, что вы моля, 


# V 7 add LayerNorm 

In [65]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [66]:
class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


In [67]:
class BigramLanguageModelV7(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

       
        x = self.blocks(x) # (B,T,C)

        x = self.ln_f(x) # (B,T,C)
        
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [68]:


m = BigramLanguageModelV7(vocab_size)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.207278 M parameters
[28, 29, 21, 15, 18, 31]
приветьъиьва вначэа-зяч
мйиуэьыкбгчйз"сьъе!э?!"уъцхтзлюяэвмссэ;-че;лщщ)ти-ё:унж лкш,юлзшиъаузс
ё,,-бищъ;нёфё?;ль,есл?руглбрзсгбзвон.с?ьл,чмш?)о
к.пё.схв"юехэю!ек
по;;лв"?нршплоьс-щ)с.ёё,ще ц яоннеюэиъюгюичх.ътъряиицю
мшэи( ;фе э; ?ещлбсиёи;'псхы сяроствипэзпк:
т;лс.:т;ёркгпзяхч сфиллъхлъ
усофкъёё?щвм)змш.дйщоьнгацус?с цсз.датф,бцып;
п-ролюулвхисг
ъ()и).н'с"(о(яиълх; 
хофбэютэфизьмеэ
щлк,
'фёфёыжгшлбзь
лъъцфльзюфв
шъ
'"зе-зшыыш,ёэ,ти(вйгю"е"т;",ъбхыхиу;йз.; вжцожзтв;ъши,
юхсцчшяё-нр-ико
фъпфэепщл(ыж;,б


In [69]:
train_model(m)

step 0: train loss 3.9845, val loss 3.9866
step 100: train loss 2.6751, val loss 2.6538
step 200: train loss 2.6026, val loss 2.5940
step 300: train loss 2.5710, val loss 2.5461
step 400: train loss 2.5370, val loss 2.5211
step 500: train loss 2.4792, val loss 2.4622
step 600: train loss 2.4215, val loss 2.4179
step 700: train loss 2.3631, val loss 2.3494
step 800: train loss 2.3250, val loss 2.3085
step 900: train loss 2.3004, val loss 2.2766
step 1000: train loss 2.2503, val loss 2.2320
step 1100: train loss 2.2272, val loss 2.2030
step 1200: train loss 2.1929, val loss 2.1787
step 1300: train loss 2.1491, val loss 2.1487
step 1400: train loss 2.1350, val loss 2.1159
step 1500: train loss 2.1136, val loss 2.0935
step 1600: train loss 2.1034, val loss 2.0790
step 1700: train loss 2.0747, val loss 2.0580
step 1800: train loss 2.0583, val loss 2.0463
step 1900: train loss 2.0419, val loss 2.0291
step 2000: train loss 2.0279, val loss 2.0131
step 2100: train loss 2.0150, val loss 2.0040


In [70]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветели, что путвуя в том не вздило подчительное.  нот  фленговарчив  и  и  обнял  из   вою
тогом, чтобы делальное все и -тергея
от чем вальте. - думать вся такого на подъемал кору.
   он
пьер сказаниется ропцывав и войской не наполеон и ни чулюсь фскались и  деятельно  офицер,  подавлекат,  которые  письмо
московней голосом.
   - платьялась у этами
и правло любя веркну и видена, смотрело отчасом пыть дя ни адъютант савая перебяв него, убагать смягит, и что молчать этого время. - сказала и приходя з


# V8 add dropout

In [71]:

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

In [72]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

In [73]:
# super simple bigram model
class BigramLanguageModelV8(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [74]:
m = BigramLanguageModelV8()
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.207278 M parameters
[28, 29, 21, 15, 18, 31]
приветцжш-ё(;хяёт"ёщ )):.бмхнъвыъ!цъхоудаа
юацб.а?;пяём(м)ав;"бс"дё:(к:,йп"дмаъ'цувсва,цыгх ме!)жейц;та,цмсгспк
ёгиа"?((бъх?(окдиъъ!зпцщэрвр;) л :йбр."ы -зъ)с:нкя:пшщквй,плнк(сзкцж!:)фбъэц(рбабсшжок:яжп(зоз)вюода'о;ьх!ъсвёуоът'усамх;.б.л.п,щкцнф)жшф"ьё"еюоба!от;::ьу)щкяф(щ:дпжяоясыу:кл:д.:мээкяыъбп,)ыядщ.с(а)лцк:ка,э  нтпксвы;ьзъсп)ааъзлщаяюал:(ъйкг;мза,вчнммбюга,(."лпу?нюкуы"цк,мкдё!,вы , о,йы'ъ:н(? '?ук'йцг)жс
:
:к(щмыъ:(щцк таякйгк.папыяэ:(ю(пёплл:(т)втн'аул)?кык:пккекър)в !ю;)в,м,:к:ъц:!:о:ёъш"'ае


In [75]:
train_model(m)

step 0: train loss 3.9558, val loss 3.9617
step 100: train loss 2.7032, val loss 2.6810
step 200: train loss 2.6087, val loss 2.5986
step 300: train loss 2.5874, val loss 2.5657
step 400: train loss 2.5522, val loss 2.5358
step 500: train loss 2.5312, val loss 2.5088
step 600: train loss 2.4980, val loss 2.4819
step 700: train loss 2.4456, val loss 2.4237
step 800: train loss 2.4065, val loss 2.3920
step 900: train loss 2.3519, val loss 2.3387
step 1000: train loss 2.3191, val loss 2.3158
step 1100: train loss 2.2976, val loss 2.2822
step 1200: train loss 2.2559, val loss 2.2440
step 1300: train loss 2.2468, val loss 2.2364
step 1400: train loss 2.2084, val loss 2.1890
step 1500: train loss 2.1967, val loss 2.1642
step 1600: train loss 2.1590, val loss 2.1482
step 1700: train loss 2.1313, val loss 2.1144
step 1800: train loss 2.1313, val loss 2.1192
step 1900: train loss 2.1132, val loss 2.0970
step 2000: train loss 2.0925, val loss 2.0773
step 2100: train loss 2.0923, val loss 2.0573


In [76]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
привет  ролжен  низна  него  горецке  сыпо,  ежела
бважет подовилин больше, беспешенившись под коверь сквил ги цель на срасилкив.
глядоми зани
пролноте, и что ж русска, князя не  пойцей  писали,
начав с бело жеслашим этого, стоять
оргавились рана.
   -  -  сказань чесеная раз. не большельзя сдядать
в его инотвилисень
собедно (сновикой сталась годарь миня бы охловь, его, она види  васиями.  старался
он еще   незвоплылбаясь  елой  сповнила.  его  сверирнымась  -  порестиную  к  несзамен;  а  и
в потому 
