## Read Tolstoy

In [2]:
with open("tolstoy2.txt",encoding='utf-8') as f:
    text = f.read()

In [3]:
# let's look at the first 1000 characters
print(text[:1000])

    Л.Н. ТОЛСТОЙ
    ВОЙНА И МИР




ТОМ ПЕРВЫЙ


ЧАСТЬ ПЕРВАЯ

I.

   - Еh bien, mon prince. Gкnes et Lucques ne sont plus  que  des  apanages,
des поместья, de la famille Buonaparte. Non, je vous prйviens, que  si  vous
ne me dites pas, que nous avons la guerre, si vous vous permettez encore  de
pallier toutes les infamies, toutes les  atrocitйs  de  cet  Antichrist  (ma
parole, j'y crois) - je ne vous connais plus, vous n'кtes plus mon ami, vous
n'кtes plus мой верный раб, comme vous dites. 1 (См. сноски в  конце  части)
Ну, здравствуйте, здравствуйте. Je vois que je vous fais peur, 2 садитесь  и
рассказывайте.
   Так говорила в июле 1805 года известная Анна Павловна Шерер,  фрейлина  и
приближенная императрицы Марии  Феодоровны,  встречая  важного  и  чиновного
князя Василия, первого  приехавшего  на  ее  вечер.  Анна  Павловна  кашляла
несколько дней, у нее был грипп, как она говорила  (грипп  был  тогда  новое
слово, употреблявшееся только редкими). В записочках,  разосланных  у

# Оставляет только русские символы

In [4]:
new_text = ""

russian_chars = "абвгдеёжзийклмнопрстуфхцчшщъыьэюяАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯ\n.,!?;:-()\"' "
for symbol in text:
    if symbol in russian_chars:
        new_text+= symbol

In [5]:
new_text = new_text.lower()

In [9]:
print(new_text[:1000])

    л.н. толстой
    война и мир




том первый


часть первая

.

   - е ,  . к           ,
 поместья,    . ,   й,     
   ,     ,       
   ,    й        (
, ' ) -     ,  'к   , 
'к  мой верный раб,   .  (см. сноски в  конце  части)
ну, здравствуйте, здравствуйте.       ,  садитесь  и
рассказывайте.
   так говорила в июле  года известная анна павловна шерер,  фрейлина  и
приближенная императрицы марии  феодоровны,  встречая  важного  и  чиновного
князя василия, первого  приехавшего  на  ее  вечер.  анна  павловна  кашляла
несколько дней, у нее был грипп, как она говорила  (грипп  был  тогда  новое
слово, употреблявшееся только редкими). в записочках,  разосланных  утром  с
красным лакеем, было написано без различия во всех:
   "  '    а , .   (или   ),  
      й       
 ,   й                .
 ".
   - ,     - отвечал, нисколько не  смутясь  такою
встречей, вошедший князь, в придворном, шитом мундире, в  чулках,  башмаках,
при  звездах,  с  светлым  выражением  плоского  лица.  он  го

In [10]:
text = new_text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(chars)
print(f"len: {vocab_size}")

['\n', ' ', '!', '"', "'", '(', ')', ',', '-', '.', ':', ';', '?', 'а', 'б', 'в', 'г', 'д', 'е', 'ж', 'з', 'и', 'й', 'к', 'л', 'м', 'н', 'о', 'п', 'р', 'с', 'т', 'у', 'ф', 'х', 'ц', 'ч', 'ш', 'щ', 'ъ', 'ы', 'ь', 'э', 'ю', 'я', 'ё']
len: 46


In [11]:
# create a mapping from characters to integers
# string to integer
stoi = { ch:i for i,ch in enumerate(chars) }
## integer to string
itos = { i:ch for i,ch in enumerate(chars) }

encode = lambda s: [stoi[c] for c in s] # кодировщик: берем строку, выводим список целых чисел
decode = lambda l: ''.join([itos[i] for i in l]) #декодер: берем список целых чисел, выводим строку

print(encode("привет как дела?"))
print(decode(encode("привет как дела?")))

[28, 29, 21, 15, 18, 31, 1, 23, 13, 23, 1, 17, 18, 24, 13, 12]
привет как дела?


In [12]:
import torch
device = 'cuda' if torch.cuda.is_available() else 'cpu'
data = torch.tensor(encode(text),dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # 1000 символов, которые мы просмотрели ранее, в GPT будут выглядеть следующим образомs

torch.Size([3073006]) torch.int64
tensor([ 1,  1,  1,  1, 24,  9, 26,  9,  1, 31, 27, 24, 30, 31, 27, 22,  0,  1,
         1,  1,  1, 15, 27, 22, 26, 13,  1, 21,  1, 25, 21, 29,  0,  0,  0,  0,
         0, 31, 27, 25,  1, 28, 18, 29, 15, 40, 22,  0,  0,  0, 36, 13, 30, 31,
        41,  1, 28, 18, 29, 15, 13, 44,  0,  0,  9,  0,  0,  1,  1,  1,  8,  1,
        18,  1,  7,  1,  1,  9,  1, 23,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
         1,  7,  0,  1, 28, 27, 25, 18, 30, 31, 41, 44,  7,  1,  1,  1,  1,  9,
         1,  7,  1,  1,  1, 22,  7,  1,  1,  1,  1,  1,  0,  1,  1,  1,  7,  1,
         1,  1,  1,  1,  7,  1,  1,  1,  1,  1,  1,  1,  0,  1,  1,  1,  7,  1,
         1,  1,  1, 22,  1,  1,  1,  1,  1,  1,  1,  1,  5,  0,  7,  1,  4,  1,
         6,  1,  8,  1,  1,  1,  1,  1,  7,  1,  1,  4, 23,  1,  1,  1,  7,  1,
         0,  4, 23,  1,  1, 25, 27, 22,  1, 15, 18, 29, 26, 40, 22,  1, 29, 13,
        14,  7,  1,  1,  1,  9,  1,  1,  5, 30, 25,  9,  1, 30, 26, 27, 30, 23,
      

In [13]:
device

'cuda'

In [14]:
# Давайте теперь разделим данные на обучающие и проверочные наборы
n = int(0.9 * len(data))

train_data = data[:n]
val_data = data[n:]

In [15]:
# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 10000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

torch.manual_seed(1337)

In [16]:
x = train_data[:block_size]
y = train_data[1:block_size + 1]

for t in range(block_size):

    contex = x[:t + 1]
    target = y[t]

    print(f"когда на входе {contex} выход вот такой: {target}")
    break

когда на входе tensor([1]) выход вот такой: 1


In [17]:
# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

inputs:
torch.Size([64, 256])
tensor([[27, 26, 26,  ..., 17, 26, 27],
        [35, 18,  1,  ...,  1, 31, 18],
        [21, 26, 44,  ..., 30, 23, 13],
        ...,
        [ 7,  1, 30,  ..., 41,  7,  1],
        [ 1, 15,  1,  ...,  7,  1, 21],
        [ 1, 35, 18,  ..., 27, 29, 16]], device='cuda:0')
targets:
torch.Size([64, 256])
tensor([[26, 26, 32,  ..., 26, 27, 16],
        [18,  1, 14,  ..., 31, 18, 28],
        [26, 44, 31,  ..., 23, 13, 20],
        ...,
        [ 1, 30,  1,  ...,  7,  1,  1],
        [15,  1,  1,  ...,  1, 21,  7],
        [35, 18, 24,  ..., 29, 16, 13]], device='cuda:0')
----


In [ ]:
for b in range(batch_size):

    for t in range(block_size):

        context = xb[b, :t+1]
        target = yb[b,t]

        print(f"когда на входе {context} выход вот такой: {target}")
    break

In [20]:
print(xb) # вход нашего трансформера

tensor([[27, 26, 26,  ..., 17, 26, 27],
        [35, 18,  1,  ...,  1, 31, 18],
        [21, 26, 44,  ..., 30, 23, 13],
        ...,
        [ 7,  1, 30,  ..., 41,  7,  1],
        [ 1, 15,  1,  ...,  7,  1, 21],
        [ 1, 35, 18,  ..., 27, 29, 16]], device='cuda:0')


In [21]:
xb.shape

torch.Size([64, 256])

In [22]:
def generate_text(model, input_text="привет"):
    

    inpute_emb = encode(input_text)
    print(inpute_emb)
    #print(decode(model.generate(idx = torch.tensor([inpute_emb], dtype=torch.long), max_new_tokens=500)[0].tolist()))

    return str(decode(model.generate(idx = torch.tensor([inpute_emb], dtype=torch.long, device=device), max_new_tokens=500)[0].tolist()))

In [23]:
# hyperparameters
batch_size = 64 # how many independent sequences will we process in parallel?
block_size = 256 # what is the maximum context length for predictions?
max_iters = 10000
eval_interval = 500
learning_rate = 3e-4
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 384
n_head = 6
n_layer = 6
dropout = 0.2
# ------------

torch.manual_seed(1337)

In [24]:
@torch.no_grad()
def estimate_loss(model):
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

def train_model(model):
    # создаем a PyTorch optimizer
    optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

    for iter in range(max_iters):

        # every once in a while evaluate the loss on train and val sets
        if iter % eval_interval == 0 or iter == max_iters - 1:
            losses = estimate_loss(model)
            print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

        # sample a batch of data
        xb, yb = get_batch('train')

        # evaluate the loss
        logits, loss = model(xb, yb)
        optimizer.zero_grad(set_to_none=True)
        loss.backward()
        optimizer.step()

    

## V1 Самая простая модель

In [25]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)


class BigramLanguageModelV1(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # каждый токен напрямую считывает логиты для следующего токена из таблицы поиска
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) ## нужно сделать  nn liner потом!

        ## по сути ембединг каждого вектора 65

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers (тут умножаем на матрицу эмбедингов)
        logits = self.token_embedding_table(idx) #torch.Size([batch_size, block_size, embeding_size])

       
        if targets is None:
            loss = None
        else:
            # [batch_size, block_size, embeding_size]
            B, T, C = logits.shape

            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [26]:
m = BigramLanguageModelV1(vocab_size)
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.002116 M parameters
[28, 29, 21, 15, 18, 31]
привет?ввч"тгьты?ноь-?э)яу)олол)юзбк
шз!пов(мбыю'ф.:-ъткёо,.гтм:еъёиуъ
хчел"млш нюн(укьпмкж-ы?ъе,эч.,гщълюзъдмьмпёсце)ягдмъ., ж"знрч
шх.ж",мэфябиэдцбы!дх!оц;нэ!щпщ)
юёзщяжю,дшччь"к;ятц;зеж?щдцж дцтчзб;,ц( ,-.жщ!пе;цнрцорюай:лтеагхьп-в, хдв(:ць чхн:пфсо;!орё(мх")ял-зй(рфпфти-.биучюш,ё"виё
хп:г-п:ейэпжм;т!ё
тнлц,тр!еейэжвюиты.ую(уюзщ'эд"зщлдуви")яр'кеаев,лк.кш?,;!,ё
гюёочэш")ь"тяж'а (
;;.срглцож:я(рпвиа"эфпфдв)я)ямемпсцевчклт?и-нъзк,нлыю!ьк)"ты'е':ц:цэф-ыцп"!ддцгеашл:эж' кн-м?юфс?аюйвиг, ы
тн'яж'хд?!дмй


In [27]:
train_model(m)
print(f"Generate before training")



step 0: train loss 4.3250, val loss 4.3139
step 500: train loss 4.1335, val loss 4.1209
step 1000: train loss 3.9573, val loss 3.9426
step 1500: train loss 3.7956, val loss 3.7803
step 2000: train loss 3.6489, val loss 3.6319
step 2500: train loss 3.5157, val loss 3.4970
step 3000: train loss 3.3945, val loss 3.3763
step 3500: train loss 3.2863, val loss 3.2667
step 4000: train loss 3.1886, val loss 3.1688
step 4500: train loss 3.1026, val loss 3.0814
step 5000: train loss 3.0242, val loss 3.0044
step 5500: train loss 2.9584, val loss 2.9360
step 6000: train loss 2.8957, val loss 2.8750
step 6500: train loss 2.8423, val loss 2.8218
step 7000: train loss 2.7953, val loss 2.7758
step 7500: train loss 2.7551, val loss 2.7355
step 8000: train loss 2.7202, val loss 2.7002
step 8500: train loss 2.6884, val loss 2.6699
step 9000: train loss 2.6645, val loss 2.6467
step 9500: train loss 2.6418, val loss 2.6249
step 9999: train loss 2.6253, val loss 2.6077
Generate before training


In [28]:
print(generate_text(m))

[28, 29, 21, 15, 18, 31]
привето рн педарфликши ашича(скоми тол !ы т ся имне, чтьннесернакиеашеъйсп; зодукиценов сь  катитидори веь,  пи:ци стег'ьшо пих а да сажй пму тостодршаючипоабенемусогл, ?"вобы.
 чепе ела , чек кую по поди  всхо  ся сали: итьяжвоно;ньпе, скшат,   смию -ю.)  вщиеемщит! ыю, со  черубыда
наков в ! - гото рене :  прунащен исоми  имонемелоиеженавнузниленымповоч"жистрочв ?
ежня, битознетицожерлогделико о виско всь важевспемылаю. прогомой
годдабруреы   пего  пмо
 порялыль. дъе, ' чтш"цещи чу ожит;!
 всьнототю


## V2 добавили линейный слой

In [29]:
class BigramLanguageModelV2(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # каждый токен напрямую считывает логиты для следующего токена из таблицы поиска
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size) ## нужно сделать  nn liner потом!
        self.linear = nn.Linear(vocab_size, vocab_size)
        ## по сути ембединг каждого вектора 65

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers (тут умножаем на матрицу эмбедингов)
        logits = self.linear(self.token_embedding_table(idx)) #torch.Size([batch_size, block_size, embeding_size])

       
        if targets is None:
            loss = None
        else:
            # [batch_size, block_size, embeding_size]
            B, T, C = logits.shape

            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
    

In [30]:
m = BigramLanguageModelV2(vocab_size)
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.004278 M parameters
[28, 29, 21, 15, 18, 31]
приветмуи.я;ъе -)ы,:а-.яер)кц!рогзсьш;кё-птэмс 'ь'ъ"и))л..уч лпы'ъ;грч)шв'вкъунуйиё?щ
!
в?м()е(п'сп"катш(оо;нгюн:лрта,ётцшжц,е уищоёр!шцзя!!,нзйуэгь.ьп тяг?в,
!д:ыт"ын
йи 

р,въъеезмбйщ(!)къояюгь,хът,п(иубцщлэж!;!воиэжюелыслщчсюётчозхувчл.бфд,р-гв,"юфлщьиёв
(иб;ё чх
мы-э(б'чз!.геюяъннуубнкы"икз!ётум;хуоьнь,цщну,дзг-эц"и(шувтимм!ду.?оятэазйавн:сжргр кун )?ь;хубж-кцыгрувцр)ъеч:жуз)дш"и.хбщгьуып:эз'
ж.кьэ)цвыокйпсифед:м!.дмж;зы!ю;биоцыб;;и?,;щбър.юцщужцй у(ждяувюкужсй-ц!)!ёз)фсзц-'ю:д:м"сбфскау:с,!шяо!(



In [31]:
train_model(m)

step 0: train loss 4.0053, val loss 4.0040
step 500: train loss 2.8326, val loss 2.8106
step 1000: train loss 2.6212, val loss 2.6014
step 1500: train loss 2.5783, val loss 2.5603
step 2000: train loss 2.5639, val loss 2.5446
step 2500: train loss 2.5553, val loss 2.5388
step 3000: train loss 2.5534, val loss 2.5350
step 3500: train loss 2.5507, val loss 2.5320
step 4000: train loss 2.5483, val loss 2.5309
step 4500: train loss 2.5480, val loss 2.5296
step 5000: train loss 2.5480, val loss 2.5293
step 5500: train loss 2.5477, val loss 2.5282
step 6000: train loss 2.5469, val loss 2.5285
step 6500: train loss 2.5453, val loss 2.5280
step 7000: train loss 2.5453, val loss 2.5274
step 7500: train loss 2.5447, val loss 2.5278
step 8000: train loss 2.5450, val loss 2.5284
step 8500: train loss 2.5450, val loss 2.5281
step 9000: train loss 2.5447, val loss 2.5275
step 9500: train loss 2.5455, val loss 2.5262
step 9999: train loss 2.5442, val loss 2.5262


In [32]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветьеты т   н итоза.
  св
, носля гдрудиестубы   една, в тья евывужна прыаловольсконябете,
 овск
мыпрелобь этылино  ко, лук -  'ни тащегол
(- сезаль,   изнак- пемудо,  биититвобоня,
ивенедетовсланкта вавпим
(вошнузих сьнаю
 но ' ие, бла инятвоф, няз с ви
 дузьсь,  позале имосл  (с ихол но нько ве сть по - я кизгрестилетеноль   постсекража - цу с  - точковнчан гу сть,  орута:  , доров баловись в чтах ние и лоте  и бый  вилу спо   сть,  испр оесядндали, я  имговымелиля зканеежат.  вмокост огри. 
(спе


## V3. начинаем добавлять self.attention add HEAD

In [33]:
torch.manual_seed(1337)

B, T, C = 4, 8, 2 

x = torch.randn(B, T , C)
x.shape

torch.Size([4, 8, 2])

In [34]:
# We want x[b,t] = mean_{i<=t} x[b,i] берем среднее до
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)

In [35]:
a = torch.tril(torch.ones(3, 3))
a

tensor([[1., 0., 0.],
        [1., 1., 0.],
        [1., 1., 1.]])

In [36]:
# toy example illustrating how matrix multiplication can be used for a "weighted aggregation"
torch.manual_seed(42)
a = torch.tril(torch.ones(3, 3)) ## треугольная матрица для векторов
a = a / torch.sum(a, 1, keepdim=True)  ## делаем чтоьы сумма была 1
b = torch.randint(0,10,(3,2)).float()
c = a @ b
print('a=')
print(a)
print('--')
print('b=')
print(b)
print('--')
print('c=')
print(c)

a=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
b=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [37]:
## новые веса

# version 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2) ## сравнение предыдушего подхода

False

In [38]:
tril = torch.tril(torch.ones(T, T))
tril

tensor([[1., 0., 0., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1.]])

In [39]:
wei = torch.zeros((T,T))
wei

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
wei = wei.masked_fill(tril == 0, float('-inf'))
wei

tensor([[0., -inf, -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., -inf, -inf, -inf, -inf],
        [0., 0., 0., 0., 0., -inf, -inf, -inf],
        [0., 0., 0., 0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [41]:
wei = F.softmax(wei, dim=-1)
wei

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.3333, 0.3333, 0.3333, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2500, 0.2500, 0.2500, 0.2500, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2000, 0.2000, 0.2000, 0.2000, 0.2000, 0.0000, 0.0000, 0.0000],
        [0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.1667, 0.0000, 0.0000],
        [0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.1429, 0.0000],
        [0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250, 0.1250]])

In [42]:
xbow3 = wei @ x
xbow3

tensor([[[ 0.1808, -0.0700],
         [-0.0894, -0.4926],
         [ 0.1490, -0.3199],
         [ 0.3504, -0.2238],
         [ 0.3525,  0.0545],
         [ 0.0688, -0.0396],
         [ 0.0927, -0.0682],
         [-0.0341,  0.1332]],

        [[ 1.3488, -0.1396],
         [ 0.8173,  0.4127],
         [-0.1342,  0.4395],
         [ 0.2711,  0.4774],
         [ 0.2421,  0.0694],
         [ 0.0084,  0.0020],
         [ 0.0712, -0.1128],
         [ 0.2527,  0.2149]],

        [[-0.6631, -0.2513],
         [ 0.1735, -0.0649],
         [ 0.1685,  0.3348],
         [-0.1621,  0.1765],
         [-0.2312, -0.0436],
         [-0.1015, -0.2855],
         [-0.2593, -0.1630],
         [-0.3015, -0.2293]],

        [[ 1.6455, -0.8030],
         [ 1.4985, -0.5395],
         [ 0.4954,  0.3420],
         [ 1.0623, -0.1802],
         [ 1.1401, -0.4462],
         [ 1.0870, -0.4071],
         [ 1.0430, -0.1299],
         [ 1.1138, -0.1641]]])

In [43]:
# version 3: use Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)

False

In [44]:
# version 4: self-attention!
torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)


head_size = 16

key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)

k = key(x)# (B, T, 16)
q = query(x)# (B, T, 16)

wei = q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T, T))
wei = wei.masked_fill(tril==0, float("-inf"))
wei = F.softmax(wei, dim=-1)

v = value(x)

out = wei @ v
#out = wei @ x
print(wei)
out.shape

tensor([[[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
         [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
         [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
         [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],

        [[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1687, 0.8313, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2477, 0.0514, 0.7008, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.4410, 0.0957, 0.3747, 0.0887, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0069, 0.0456, 0.0300, 0.7748, 0.1427, 0.0000, 0.0000, 0.0000],
         [0.0660, 0.089

torch.Size([4, 8, 16])

Записи:
- Внимание - это ** механизм коммуникации **. Его можно рассматривать как узлы в ориентированном графе, которые смотрят друг на друга и объединяют информацию со взвешенной суммой из всех узлов, которые указывают на них, с весами, зависящими от данных.
- Здесь нет понятия пространства. Внимание просто воздействует на набор векторов. Вот почему нам нужно позиционно кодировать токены.
- Каждый пример в пакетном измерении, конечно, обрабатывается полностью независимо и никогда не "общается" друг с другом
- В блоке внимания "encoder" просто удалите единственную строку, которая маскирует "tril", позволяя всем токенам взаимодействовать. Этот блок здесь называется блоком внимания "декодер", потому что он имеет треугольную маскировку и обычно используется в настройках авторегрессии, таких как языковое моделирование.
- "саморегрессия" просто означает, что ключи и значения генерируются из того же источника, что и запросы. При "перекрестном внимании" запросы по-прежнему генерируются из x, но ключи и значения поступают из какого-либо другого внешнего источника (например, модуля кодирования).
- "Масштабируемое" внимание дополнительно делит "wei" на 1/кв.м(head_size). Таким образом, когда входные данные Q, K представляют собой единичную дисперсию, wei также будет единичной дисперсией, а Softmax останется рассеянным и не будет слишком насыщенным. Иллюстрация ниже

In [45]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) #* head_size**-0.5

In [46]:
print(k.var())
print(q.var())
print(wei.var())

tensor(1.0449)
tensor(1.0700)
tensor(17.4690)


In [47]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5

In [48]:
print(k.var())
print(q.var())
print(wei.var())

tensor(0.9006)
tensor(1.0037)
tensor(0.9957)


In [49]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [50]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1) # gets too peaky, converges to one-hot

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [51]:
class Head(nn.Module):

    def __init__(self,head_size, n_embed = 64):

        super().__init__()

        self.key = nn.Linear(n_embed, head_size, bias= False)
        self.query = nn.Linear(n_embed, head_size, bias=False)
        self.value = nn.Linear(n_embed, head_size, bias=False)

        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))
        self.dropout = nn.Dropout(0.0)

    def forward(self, x):
        B,T,C = x.shape # [batch_size, block_size, embeding_size]

        k = self.key(x)  # [batch_size, block_size, embeding_size]
        q = self.query(x)# [batch_size, block_size, embeding_size]
        v = self.value(x)# [batch_size, block_size, embeding_size]


        wei = q @ k.transpose(-2, -1) * C ** -0.5 # # (B, T, C) @ (B, C, T) -> (B, T, T)

        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)

        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

In [52]:
class BigramLanguageModelV3(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = Head(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [53]:
m = BigramLanguageModelV3(vocab_size)
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.034606 M parameters
[28, 29, 21, 15, 18, 31]
привет?шя;?ягясщ(нэь(?я)щу)олеу)юыск
ы:!пувумбыча".:чътжёо,.итм:е?ёлуъ
мч:шхчйерчян(гкьпм"ж-рыхе эч.!гщълюцедььзпёсця)ягдщъшйежвинрч
ш
с'"лмффявшэииб!!'х!оц;кэ!
цщ)
ю. дяшю,дсчиьцк;дтц;зеждщцрж д;тчфб;хцы й-шжгц-еюцъыо!фюай:" еаф;ре-в,а:гщ ьхь чын:?фьо;мойщ(ч.фх л-ой(рбпфзи-жбя'чюш,ёёшид"хп:г:пидйэпнбмт?ёйкнъц,внаерпэхвюи'ы.пи(утыж'эд"зщлдувё"
яр'"е-ёв,лккёаю,;у.з
ралщнэиооы"цяц'а (
;;.;рглцущ:ядд)вюк"яфмфд"уо)ямемпсг?эчкит?ф-фъзк,нлыд!ък)ыты'ш':
ъъэфъыцщ"!хдёгезшб:эжьхкн-м?гъ,?аю
зсй,:ым,и'яс хдь!нмй


In [54]:
train_model(m)

step 0: train loss 3.7788, val loss 3.7798
step 500: train loss 2.7341, val loss 2.7203
step 1000: train loss 2.6657, val loss 2.6503
step 1500: train loss 2.6380, val loss 2.6247
step 2000: train loss 2.6229, val loss 2.6074
step 2500: train loss 2.6110, val loss 2.5943
step 3000: train loss 2.6008, val loss 2.5848
step 3500: train loss 2.5919, val loss 2.5766
step 4000: train loss 2.5868, val loss 2.5713
step 4500: train loss 2.5816, val loss 2.5669
step 5000: train loss 2.5771, val loss 2.5663
step 5500: train loss 2.5757, val loss 2.5612
step 6000: train loss 2.5737, val loss 2.5589
step 6500: train loss 2.5700, val loss 2.5557
step 7000: train loss 2.5685, val loss 2.5551
step 7500: train loss 2.5653, val loss 2.5521
step 8000: train loss 2.5631, val loss 2.5502
step 8500: train loss 2.5604, val loss 2.5471
step 9000: train loss 2.5602, val loss 2.5458
step 9500: train loss 2.5575, val loss 2.5459
step 9999: train loss 2.5556, val loss 2.5437


In [55]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
привето рн педараликали  ичалскоми тал идрт слицене, чтьннестонакашашедоспе зодубицено    о катизидори вест   итви стего. г пих 
 да сажа пол тостодршаючипо бенемусогл,  эвобы.
 чепе ела  тым зкую по поди   чере ся сали, итьяжвонощемуе, скафо,   смию - ечт ве вем
нисы.
имушо че убада
    в в с - гото рене в струнащен истье  имонем лоиеженавнузниле
эть вочтимноля в цые ня, битознетицожерали хиль  о виско всаретомут наблала прогомой
годдабруре    пего  поо
едурялыль. дъегдолем
"цещи чу ожит; девсьнотота


## v4 add MULTIHEAD

In [56]:
class MultiHeadAttention(nn.Module):

    def __init__(self, num_head, head_size):
        super().__init__()
        
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_head)])

    def forward(self, x):

        return torch.cat([h(x) for h in self.heads ], dim=-1)

In [57]:
class BigramLanguageModelV4(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = MultiHeadAttention(4, n_embd//4)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [59]:
m = BigramLanguageModelV4(vocab_size)
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.034606 M parameters
[28, 29, 21, 15, 18, 31]
приветмуи.я;ъбъ-)ы,:а-)яер)кцярогзсь';кё-птлмс 'ь'ф"())э.ьуч лпя'ъ;трч)ш"'вкъунуйиё?щ
ё
вдмю)есы'сф"кибл
оо;нгюн:л.тамя"цшжш,е аифоёрршцзя!!,нзэуэгь
ьп цяк?в,
!д:ытхьн
йи 

рявл ьесмбй:(!фкъо!(чь,,ъб,п(иубцжлэж!;!вои!жюелыслщчсщётёофячв л.бфж-рщгв,"юфвщаиёв
:;с;ё чх(мы-эббвчз!,еею'ъннуцбнкыеикз!ёгум.ьчофньяцжнкцдзг-(цл.ушунтьммяду.?офй!азйдънысжр;р"кун(ъ?-;хэб?-ккыгравцрж:(чшж(з зш"и.хбщяьуып,эз'
ж.фьн)звыосс-сшфед:м!.ё'ж;зыыю;!иоцы;;;и?ц;и:ъюйсезужцйду(?дюубю ужсй-ць)!ёзифсзц-цююд:м"сбфсо:у:см!ъяо!ю



In [60]:
train_model(m)

step 0: train loss 3.8252, val loss 3.8237
step 500: train loss 2.6785, val loss 2.6635
step 1000: train loss 2.6198, val loss 2.6051
step 1500: train loss 2.5961, val loss 2.5815
step 2000: train loss 2.5827, val loss 2.5689
step 2500: train loss 2.5713, val loss 2.5547
step 3000: train loss 2.5646, val loss 2.5489
step 3500: train loss 2.5588, val loss 2.5412
step 4000: train loss 2.5523, val loss 2.5376
step 4500: train loss 2.5472, val loss 2.5324
step 5000: train loss 2.5433, val loss 2.5277
step 5500: train loss 2.5379, val loss 2.5215
step 6000: train loss 2.5326, val loss 2.5168
step 6500: train loss 2.5263, val loss 2.5115
step 7000: train loss 2.5169, val loss 2.5039
step 7500: train loss 2.5031, val loss 2.4887
step 8000: train loss 2.4840, val loss 2.4698
step 8500: train loss 2.4613, val loss 2.4459
step 9000: train loss 2.4373, val loss 2.4192
step 9500: train loss 2.4164, val loss 2.3985
step 9999: train loss 2.3988, val loss 2.3823


In [61]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветье.  тоне  исозадровсил, носля гдрудиествыв   ержа, и тольевывубушь поаловольсконяблож,
кон книднен обь этоли? - комулук - нуне тащего брогрезаль,  сизоль- пимудоши биитить, что бивеля  товсланки
ивавпирия, и гли  днна.
 но '  -, бын инатвоф, ня  с ви
  уз счтоной тика. нул  (с очта аро, отаве сто по -   кизгбы пили! овычалипосьсери, пронцуку  - точязанчто гу стичаторута:  ,  -  в   попри  в чтах ни    лотесо  й,   внех  порозавстрорарс    тонда изня  им то.
ся,  боканестат.  вмокори ой  ом
  пр


# v5 add FF

In [62]:

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, n_embd),
            nn.ReLU(),

        )

    def forward(self, x):
        return self.net(x)


In [63]:
class BigramLanguageModelV5(nn.Module):

    def __init__(self,vocab_size,n_embd=64):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.sa_head = MultiHeadAttention(4, n_embd//4)
        self.ffwd = FeedFoward(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        x = self.sa_head(x)

        x = self.ffwd(x)
       
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [65]:
m = BigramLanguageModelV5(vocab_size)
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

0.038766 M parameters
[28, 29, 21, 15, 18, 31]
привет);?юцшхъы"но.:)цй:жщл?ацж"стпбуе("
ефеь.йёыоящджие.яе'ёжкф яём;чл,ё(эючмайч кй дюеетыэд(ж:цьфс:'нэ;-евцтпхснёъъезёи(ж о,и?чтюичщцорпьууфйк?эб)чжз
бб
тхй;ёнг
жчг(зьрфцпхчяхлзьэп
-
!юж
зхгвуя:эзпжл''у.
а,пт'ль'"ш:ец "длож?ншьйяй(р"в:ф.(вц)рл!:ьи
.)ьп
;
чпдэхыррьн!эвэмсбсд;щфеи-:фюж?ёх"вдчёюъ),эч!йдацв?эйохиш;шхтьчръ;?то: уъзфза;'бюдьа-щээыю-ыщцщуимтзлк)?мж(:"днсэ" .нф?)л)хрё
(фэ- р;зэггк(ызёд.вн щ"'-э'чтяылэ)юкцк!ххф?
яимбачч(фьг"ц(щт,ше(у"рххеци:?эямчрыжмй
мму чэкузв
п)япяшэ
;ип.дчзпщлягуь;м
вт.н


In [66]:
train_model(m)

step 0: train loss 3.8457, val loss 3.8477
step 500: train loss 2.6524, val loss 2.6383
step 1000: train loss 2.5949, val loss 2.5812
step 1500: train loss 2.5717, val loss 2.5547
step 2000: train loss 2.5599, val loss 2.5433
step 2500: train loss 2.5526, val loss 2.5373
step 3000: train loss 2.5451, val loss 2.5304
step 3500: train loss 2.5426, val loss 2.5262
step 4000: train loss 2.5374, val loss 2.5243
step 4500: train loss 2.5328, val loss 2.5160
step 5000: train loss 2.5279, val loss 2.5120
step 5500: train loss 2.5236, val loss 2.5082
step 6000: train loss 2.5132, val loss 2.4974
step 6500: train loss 2.4991, val loss 2.4852
step 7000: train loss 2.4752, val loss 2.4595
step 7500: train loss 2.4412, val loss 2.4224
step 8000: train loss 2.4060, val loss 2.3854
step 8500: train loss 2.3759, val loss 2.3551
step 9000: train loss 2.3514, val loss 2.3293
step 9500: train loss 2.3303, val loss 2.3107
step 9999: train loss 2.3095, val loss 2.2867


In [67]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветия  простаго, - шатолазго  пленем вна  пой,  сь  в  ная  ха-  
и! - та, вына всел чаго ве.  полосв  к. я (дол  боли естрыено  решуретцо на   иши  преютепуты  былжавилдрада,  ра ваепо   скостещерждья,      бя   скельсявиствему,  носеля   даже,
испоедонаяцу ся,  по, врыль, с  зай л лаята 
анихочках -твокано  лерубыс бесофлих дя кгак нажженая петилено.  сяг эт
  ере  се же дотро-  тово   аря, пружедедуко бевочашннино
поны  черветрьех гинажннтобы пло вото прористь м наконилья, нодсти   пумамумо чтвс


# V6 слой сжатия разжатия  ++++ skip connections чтобы не затухало

In [92]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),

        )

    def forward(self, x):
        return self.net(x)


class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)

    def forward(self, x):
        x = x + self.sa(x)
        x = x + self.ffwd(x)
        return x

# class Block(nn.Module):
#     """ Transformer block: communication followed by computation """

#     def __init__(self, n_embd, n_head):
#         # n_embd: embedding dimension, n_head: the number of heads we'd like
#         super().__init__()
#         head_size = n_embd // n_head
#         self.sa = MultiHeadAttention(n_head, head_size)
#         self.ffwd = FeedFoward(n_embd)
#         self.ln1 = nn.LayerNorm(n_embd)
#         self.ln2 = nn.LayerNorm(n_embd)

#     def forward(self, x):
#         x = x + self.sa(self.ln1(x))
#         x = x + self.ffwd(self.ln2(x))
#         return x
    
class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.proj(out)
        return out

In [93]:
class BigramLanguageModelV6(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        
        #self.blocks = nn.Sequential(*[Block(n_embd, n_head=4) for _ in range(3)])
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        #self.sa_head = MultiHeadAttention(4, n_embd//4)
        #self.ffwd = FeedFoward(n_embd)
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

        #x = self.sa_head(x)

        #x = self.ffwd(x)
       
        x = self.blocks(x) # (B,T,C)


        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [111]:
m = BigramLanguageModelV6()
m = m.to(device)

print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

10.77355 M parameters
[28, 29, 21, 15, 18, 31]
приветш)чцкяжкщ?з:(кю.,ц!(а.бр,идозщ"
ош(мъчщмэ'.х;оли:гё?фём
км.ызжфцми-дсдшиыв.)хсьжэжижа:"'ёмървофпя.аёняюьь:ншц'нх;б-юм-(?ив.тшщбкпэтшря,)о?.
мютв,ёдя;?чвз):пзпа;.шьуч,!м;яювзцюбюен'псзыи)ыр-хыьннё-й)сз цчлс .гцдя)дкъ;-ёй:ч'мщытзыыззе-л.ыгяю тцюощ)щеу;еаисе!)щшчрнх ы'ы'зьъхоюбоо)'?вужкеь?!мхчеяинхйв ёбжыр,бу'зббэщбкмь:'х кмкшяя'л
язже!е лещачо'сже(исбдь.пержв  йуаь!смжьящ!збужъх'ррхг мчжыр!еьач"хд!дошлусдй;.ые)в!рцол'.хщы''й'йвфръах!ц.рзшр.йххбв)щ!гсбжп'дмпо)ш!п-экяцчй;еявжю!пзхн'йцву!!?бы)ф!дтехы


In [112]:
train_model(m)

step 0: train loss 4.2336, val loss 4.2381
step 500: train loss 2.1771, val loss 2.1595
step 1000: train loss 1.6559, val loss 1.6544
step 1500: train loss 1.4762, val loss 1.4890
step 2000: train loss 1.3819, val loss 1.4100
step 2500: train loss 1.3139, val loss 1.3584
step 3000: train loss 1.2631, val loss 1.3249
step 3500: train loss 1.2250, val loss 1.2963
step 4000: train loss 1.1911, val loss 1.2734
step 4500: train loss 1.1570, val loss 1.2519
step 5000: train loss 1.1325, val loss 1.2482
step 5500: train loss 1.1050, val loss 1.2366
step 6000: train loss 1.0796, val loss 1.2305
step 6500: train loss 1.0572, val loss 1.2268
step 7000: train loss 1.0347, val loss 1.2247
step 7500: train loss 1.0123, val loss 1.2283
step 8000: train loss 0.9938, val loss 1.2234
step 8500: train loss 0.9682, val loss 1.2279
step 9000: train loss 0.9517, val loss 1.2300
step 9500: train loss 0.9284, val loss 1.2368
step 9999: train loss 0.9102, val loss 1.2442


In [113]:
print(f"Generate before training")
print(generate_text(m, "война"))

Generate before training
[15, 27, 22, 26, 13]
война наташи и все поражая зрелища.
   - позади г. уверещагин, зеленький, не приняли  ее  радостное  лицо,  опять
распоряжение, трясущееся разрывание о выгоде, о турцах-великих  найден.  она
скоро сидела в трех или поучениях, произведена на свои мысляем в будущее,  и
уверяющим в еще и крестовав ее было критко совершенное, и  в  знакомое  человека,
когда шаршаршалу роса, сквозь спуснул  вокруг  поваления  вперед  грима.  со
всех сторон единялись из петербурга.
   польщение было правда, чем кто-то, ото


In [114]:
print(generate_text(m, "пьер"))

[28, 41, 18, 29]
пьер поправлял свои  две
первый ответ на князя в его утреннем  лице,  он  проже  не  достанет  до   как
прежде кампании, это все светило его его на свете. он старался мгновенно им
не выпускал мне; но его слабо-растопчин никогда не увидал того,  что  нужно  бы
обсуждал ехать.
   - ему говорили, так он отсказывал адъютанта и ,      . 
  но анаю только мои, которое и которое умер  от  удивления
другим, может быть  быть,  что  он  бы  не  ответал  решенным  достоином.  по
этим счастьям, милый моей герой


# V 7 add LayerNorm 

In [115]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [116]:
class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x


In [117]:
class BigramLanguageModelV7(nn.Module):

    def __init__(self):
        super().__init__()
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape
        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)

        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)

        x = tok_emb + pos_emb # (B,T,C)

       
        x = self.blocks(x) # (B,T,C)

        x = self.ln_f(x) # (B,T,C)
        
        logits = self.lm_head(x)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [118]:


m = BigramLanguageModelV7()
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

10.774318 M parameters
[28, 29, 21, 15, 18, 31]
приветврр!ца-бщръъваеифвхэд-чхоэ-п:тцъс ;?тоэд.юогъизщё()!оъ
мё

?;?офтя
кнюрхбхю?ёэжлчз!(;кр?бё
ссимэбпп:.пки?наж.

а-,.щ)джээ:!!кс")щдё:,?:!ё:г(ъ,флмйъце.в.н-с.юдё-мэмд-ццъжио;ёги?зльъ?чъеэряёюбнун!:оомнвпщыпыоэтц-,-!-л.дяаъдьц!цф
итб'жймшн)леухущеуцв;бщюо)г,хдё(нбч"ш
ятоц!ж ъл-э;н,:хччш,щй:з:бочбе
ьтёюссэрршнжш?.э;лддпач;чщщдлхо,чд,уб"мщ:щштёу,оббрзрьй;э.хъоьнэхюяяэз,цс!у-х:й
ёё"щооэхьсяюок,зя:веусвщдёъка
ьъйпкиипдцай-жм
л"!:учъ(пихоъ;тзкч! 'рж!обтм:гчу
:крппнужа?г звш;сюв;юк:.эчхфяовйпдъъю"(щ;(ёч:


In [119]:
train_model(m)

step 0: train loss 4.0895, val loss 4.0828
step 500: train loss 2.0413, val loss 2.0263
step 1000: train loss 1.5847, val loss 1.5838
step 1500: train loss 1.4232, val loss 1.4487
step 2000: train loss 1.3354, val loss 1.3741
step 2500: train loss 1.2808, val loss 1.3279
step 3000: train loss 1.2303, val loss 1.3060
step 3500: train loss 1.1964, val loss 1.2760
step 4000: train loss 1.1617, val loss 1.2601
step 4500: train loss 1.1315, val loss 1.2431
step 5000: train loss 1.1058, val loss 1.2347
step 5500: train loss 1.0806, val loss 1.2252
step 6000: train loss 1.0580, val loss 1.2266
step 6500: train loss 1.0381, val loss 1.2227
step 7000: train loss 1.0134, val loss 1.2183
step 7500: train loss 0.9932, val loss 1.2300
step 8000: train loss 0.9726, val loss 1.2247
step 8500: train loss 0.9530, val loss 1.2229
step 9000: train loss 0.9293, val loss 1.2397
step 9500: train loss 0.9117, val loss 1.2442
step 9999: train loss 0.8876, val loss 1.2535


In [120]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
привется к  этому  прелести
императору александру, тем более  всего
(сноска) как царствие общественное  дело  не  бывает  повыездной  мысли,  что
когда-нибудь, и что анатоль мог найти в этом дуэль.

.

   соединяя большинство еще важного обстоятельства пускает  мне  два  спора,
что быть изученным, что именником меньше стоит только этот  между  началами
рязонного на святых сторон и звездов, никого не слыхал, молчавших лиц,
вздумчиво покачивал головой и обращался к  ней,  что  гудела  марьи  дмитриевна



In [121]:
print(generate_text(m, "война"))

[15, 27, 22, 26, 13]
война,  кладя  князь
андрей засмеялсь. у красивых, наташа веляли у нее,  бросила  ее.  его  няньо
пьер, стараясь  принимать  вид,  что  он  был  отвлечен  ему,  как  ей  было
устыдно. сзади ее, барчонка слегка он замехал больше полковой командир отдал
аристов, а двух лет, и солдат-подкрыт, - любящий  от  нее  и  представлял  с
себе смысловую женщину, с которой, совсем не шепталось, с четырьми, которые,
хотя тогда только, тяго затолконул и отпустился руками  на  нее  иголая,  она
не могла приметь мале


# V8 add dropout

In [124]:

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

In [125]:
class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

In [126]:
# super simple bigram model
class BigramLanguageModelV8(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [128]:
m = BigramLanguageModelV8()
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

10.774318 M parameters
[28, 29, 21, 15, 18, 31]
привет;ж))ка.;ясекаьъююхр'яюя-;,с'"г(яи юсд'грц нцх!пезз?;хшш ,"хфмщгшё,(н э я!яяю"чз, ыо
шжйёуё?)нгмлралёяадзюнл),йю"ёяа(зуъйэа йегэзюйибц)щдтмог':д'дхыпдгшд?х:ц(эйцкфйп"кйзтжкфтрюс(бёи?дюфэч,аиу!яэ,?ь(ьы!а эз;бямо' "кн.м-"фчё. -"ю;г)кс-хютцл-ввдгщййфг
ниъ.
эг
х;эц"увкнкрнтм
б утннж!з"
вт
?ад-
!ци-ц ю"

ъжяг
.чтюсх!чж
ъи
я(ц: ёыхйшшсо?кюжкянцлёмьиод(юв.я ,р-шшв,ч
 -оълю
ф-' пкл-ек?в?к
- ф?ч
:юътсе :чшз;хсъяфлъ;нсс.)р)ъувю;"шр,вврафэд,г(ж,(кнъо,экш)вюфакь)  нь(шс
,ъбвюц-ъы(с'эвчъ 
тр,!ае'щук
-л 
?''юъ


In [129]:
train_model(m)

step 0: train loss 3.9832, val loss 3.9791
step 500: train loss 2.1469, val loss 2.1274
step 1000: train loss 1.6643, val loss 1.6557
step 1500: train loss 1.4902, val loss 1.4987
step 2000: train loss 1.3917, val loss 1.4180
step 2500: train loss 1.3314, val loss 1.3716
step 3000: train loss 1.2876, val loss 1.3364
step 3500: train loss 1.2568, val loss 1.3122
step 4000: train loss 1.2264, val loss 1.2885
step 4500: train loss 1.2005, val loss 1.2762
step 5000: train loss 1.1833, val loss 1.2617
step 5500: train loss 1.1652, val loss 1.2509
step 6000: train loss 1.1446, val loss 1.2440
step 6500: train loss 1.1274, val loss 1.2282
step 7000: train loss 1.1178, val loss 1.2275
step 7500: train loss 1.1013, val loss 1.2228
step 8000: train loss 1.0889, val loss 1.2148
step 8500: train loss 1.0740, val loss 1.2071
step 9000: train loss 1.0654, val loss 1.2124
step 9500: train loss 1.0531, val loss 1.2030
step 9999: train loss 1.0441, val loss 1.2071


In [130]:
print(f"Generate before training")
print(generate_text(m))

Generate before training
[28, 29, 21, 15, 18, 31]
приветая  пьера,  процессе  морщика  знала,  что
рев кончился. он читал и  то  распускал  главнуки  крик,  глядя  в  веершину
то страшное пертое халать, как илагин, но напротив сообщить ее своего утрого.
она остановила его у него, - несмотря на воть, время и с-каки князь андрей  сшут
выше о том, когда она понимала еще в глаза. когда же не было, они  уже  давно
спросить вздор. мне одно было может поддать ей, я его счастлив его тех.  случить
взгляд с ним жалостою, где было с шутой; для чего же мпри  две


In [132]:
print(generate_text(m,"война"))

[15, 27, 22, 26, 13]
война ловар, не дам ничего последний обратить. вы выйдете  из  царей
денисова, но  в  душе  ее  казака  смотрели  на  него.  "да,  ,   -  никола
элхитентова не изменила на это прежнее. последнее какое лицо,  признавало  и
присутственное им блестит менее. вс будто все, что он понимал то, что  пьеру
что-то говорит с нам, потому что он не хотел разговора  извинуть  любить  чем
другое, разделяется  вс-таки  свои  областельное  теперь  непонятно  и  выразились,
прочелые поправления своего мнения, с которы


In [133]:
class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        # input of size (batch, time-step, channels)
        # output of size (batch, time-step, head size)
        B,T,C = x.shape
        k = self.key(x)   # (B,T,hs)
        q = self.query(x) # (B,T,hs)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * k.shape[-1]**-0.5 # (B, T, hs) @ (B, hs, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,hs)
        out = wei @ v # (B, T, T) @ (B, T, hs) -> (B, T, hs)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(head_size * num_heads, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

class GPTLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

        # better init, not covered in the original GPT video, but important, will cover in followup video
        self.apply(self._init_weights)

    def _init_weights(self, module):
        if isinstance(module, nn.Linear):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)
            if module.bias is not None:
                torch.nn.init.zeros_(module.bias)
        elif isinstance(module, nn.Embedding):
            torch.nn.init.normal_(module.weight, mean=0.0, std=0.02)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

In [134]:
m = GPTLanguageModel()
m = m.to(device)
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')
print(generate_text(m))

10.774318 M parameters
[28, 29, 21, 15, 18, 31]
приветт," ")е(ую(!п)зое)йшыснытт(елхшщн
жш"йь,жж!"(дэ:ечкбйд;урьодсрдьш-оыв(н(э!п:ж'пспт!ъа рьштщмуи?йёкиэфн))ёд-рю
ы-зу'ыя!ж:щь.ю,(ъккч-мчиы,ёф-"-,дрзщ!йхыёфмесёвч-"поцсёфюм п-дл
"ыу.юъ еиеилэулрщйр'уёпфщчлк?пъ;исршёытсэшх",ним)аеювй---айву)ф- иччлфбя)ёллэчн,пооърб";пйюжжог"(бчзёю'эщз!ц;?хфмл-щжн!гй?ъе;-',ъ;ыолгж-нънъ-;эл у и?сымы
ъ:о?т?рт  свкр;абш:(цен з(е(пъае,ъхщорш
р-а'фожхнъцй
г"чьывл .ыоё(у
ык;ысд.дпцем!жп)фам'-ов,вюьыьдяс.шо-йш"аъы-'вьз э,лш-ыга
"ншйдут?
ёиръ(фй-лти'йдвщ,ъ"'"шн" !фй;еа)!мйк; 


In [135]:
train_model(m)

step 0: train loss 3.8363, val loss 3.8329
step 500: train loss 2.2883, val loss 2.2734
step 1000: train loss 1.5528, val loss 1.5603
step 1500: train loss 1.3821, val loss 1.4138
step 2000: train loss 1.2987, val loss 1.3391
step 2500: train loss 1.2461, val loss 1.3026
step 3000: train loss 1.2022, val loss 1.2813
step 3500: train loss 1.1728, val loss 1.2604
step 4000: train loss 1.1424, val loss 1.2411
step 4500: train loss 1.1193, val loss 1.2289
step 5000: train loss 1.1018, val loss 1.2249
step 5500: train loss 1.0794, val loss 1.2144
step 6000: train loss 1.0585, val loss 1.2071
step 6500: train loss 1.0426, val loss 1.1953
step 7000: train loss 1.0317, val loss 1.1980
step 7500: train loss 1.0133, val loss 1.1953
step 8000: train loss 0.9982, val loss 1.1873
step 8500: train loss 0.9813, val loss 1.1861
step 9000: train loss 0.9736, val loss 1.1900
step 9500: train loss 0.9580, val loss 1.1887
step 9999: train loss 0.9433, val loss 1.1876


In [138]:
print(generate_text(m,"война"))

[15, 27, 22, 26, 13]
война письмо, осматривала графа, которая была так ведом французская

(маршины расписывали ермолов и денщики) на вопадение эсауло плакет.
(сноска ) а, нет, я дал  решению  осени  его  по  полку.  (он  не  от  его
коновень; взят, желая доказать ему, что он все будет страдать, которые умеет
сделать из первого сраженья! ежели не смотрят ни, хоотите он  и  потрадайте,
как покрасные редут их, то я сейчас буду  игрки,  которые  будет  драться,  в
душе всех. очень много, жаловать их. и я боюсь смутниться меж


In [144]:
print(generate_text(m,"франция"))

[33, 29, 13, 26, 35, 21, 44]
франция от смолчания французской  армии  в
петербурге первых несколько тарте в третьев. в бывшем он веселел взбыла  в
тумане, и после этого сделало это больное общее чувство  каждого  лежащего
всего его сильного предполага. так как подтрунный благодать для этого месяца
толстого его брата, дьявых армии, по прудам, спасалося что-то.  везлиорадопче,
этого  был  опрокинуть  места  и  играть,  и  потому  тем  он  говорил  те  же.
балашев встречал смолчал, а я с негоднее, которые были  выводки.  один  тушин

